# This file contains a list of pre-commit hooks that will run for a package
# List of available hooks can be found here: https://pre-commit.com/hooks.html

# To use pre-commit hooks:
# Install in your environment (only has to be done once):
#   $ pip install pre-commit
# Install for your package (once per package, from within your package's path)
#   $ pre-commit install

repos:

# black python formatting
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      args: [--line-length=120]

# isort python package import sorting
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: ''
    hooks:
    -   id: isort